version: '3'
services:
  web:
    build:
      context: ./web
    ports:
      - "8081:8081" # Map container port 8081 to host port 8081
    # Add any additional configuration here

  express-backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
    # Add any additional configuration here

  mobile:
    build:
      context: ./mobile
    image: mobile
    ports:
      - "8082:8082"  # Map container port 8082 to host port 8082

  apksaver:
    image: mobile
    volumes:
      - ./apk-output:/apk-output
    command: /bin/sh -c "cp /app/app-release.apk /apk-output/"
